### ISSUE TITLE
Demos don't seem to work anymore

### ISSUE THREAD

**Issue by markknol** [jackwlee01/pixi-flump-runtime#31]
https://cdn.rawgit.com/jackwlee01/pixi-flump-runtime/master/examples/js/dog/bin/index.html
https://cdn.rawgit.com/jackwlee01/pixi-flump-runtime/master/examples/js/monster/bin/index.html

```
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at i.updateTexture (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js:5:3429)
    at i.renderBatch (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js:6:17956)
    at i.flush (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js:6:17756)
    at i.renderDisplayObject (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js:5:2445)
    at i.render (https://cdnjs.cloudflare.com/ajax/libs/pixi.js/3.0.11/pixi.min.js:5:2203)
    at animate (https://cdn.rawgit.com/jackwlee01/pixi-flump-runtime/master/examples/js/dog/bin/main.js:29:12)
```

**Comment by jackwlee01** [comment]
I've updated the demo pages.

I have also updated for the latest version of the haxe pixi externs. Looks like there is now a bug, which I'll take a look at on the weekend. It's been a while since there has been any interest in this project, so it is relatively unmaintained. I'm more focused on my Kha renderer for Flump. Happy to share that project if it is of any interest.

**Comment by jackwlee01** [comment]
Bugs fixed. Closing.

**Comment by markknol** [comment]
Thanks!
